/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1p1_lisadiazdelvalle;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Random;

/**
 *
 * @author HTS
 */
public class Menu extends javax.swing.JFrame {

    public ArrayList<Cancion> song = new ArrayList<>();
    public int seleccionada;
    Random aleatorio = new Random();
    //public Random randon = new Random();

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labotify = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        listar = new javax.swing.JButton();
        informacion = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        backmenu = new javax.swing.JButton();
        Agregar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Labelcancion = new javax.swing.JLabel();
        Labelartista = new javax.swing.JLabel();
        Labelalbum = new javax.swing.JLabel();
        Labelaño = new javax.swing.JLabel();
        Labelduracion = new javax.swing.JLabel();
        scancion = new javax.swing.JScrollPane();
        cancion = new javax.swing.JTextPane();
        salbum = new javax.swing.JScrollPane();
        album = new javax.swing.JTextPane();
        sartista = new javax.swing.JScrollPane();
        artista = new javax.swing.JTextPane();
        saño = new javax.swing.JScrollPane();
        año = new javax.swing.JTextPane();
        sduracion = new javax.swing.JScrollPane();
        duracion = new javax.swing.JTextPane();
        Agregar1 = new javax.swing.JButton();
        saliragregar = new javax.swing.JButton();
        Modificar = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonguardarcambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cambiarnombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cambiaralbum = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        cambiarartista = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        cambiaran = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        cambiarduracion = new javax.swing.JTextPane();
        Recursion = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        botongobinario = new javax.swing.JButton();
        botonmatrices = new javax.swing.JButton();
        backMenurecursion = new javax.swing.JButton();
        Conversiones = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        botonbinariodecimal = new javax.swing.JButton();
        botondecimalbinario = new javax.swing.JButton();
        backmenurecursion = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recursion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        golabotify = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(243, 186, 231));

        jLabel2.setBackground(new java.awt.Color(255, 153, 204));
        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("Labotify");

        agregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        agregar.setText("Agregar");
        agregar.setMargin(new java.awt.Insets(8, 14, 3, 14));
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setMargin(new java.awt.Insets(8, 14, 3, 14));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        listar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        listar.setText("Listar");
        listar.setMargin(new java.awt.Insets(8, 14, 3, 14));
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        informacion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        informacion.setText("Informacion");
        informacion.setMargin(new java.awt.Insets(8, 14, 3, 14));
        informacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionMouseClicked(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        modificar.setText("Modificar cancion");
        modificar.setMargin(new java.awt.Insets(8, 14, 3, 14));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });

        backmenu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        backmenu.setText("Menu");
        backmenu.setMargin(new java.awt.Insets(8, 14, 3, 14));
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(134, 134, 134))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar)
                    .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(12, 12, 12)
                .addComponent(listar)
                .addGap(18, 18, 18)
                .addComponent(informacion)
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addComponent(backmenu)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LabotifyLayout = new javax.swing.GroupLayout(Labotify.getContentPane());
        Labotify.getContentPane().setLayout(LabotifyLayout);
        LabotifyLayout.setHorizontalGroup(
            LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LabotifyLayout.setVerticalGroup(
            LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setText("Agrega un canción");

        Labelcancion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Labelcancion.setText("Canción");

        Labelartista.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Labelartista.setText("Artista");

        Labelalbum.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Labelalbum.setText("Album");

        Labelaño.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Labelaño.setText("Año");

        Labelduracion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Labelduracion.setText("Duración");

        cancion.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        scancion.setViewportView(cancion);

        album.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        salbum.setViewportView(album);

        artista.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        sartista.setViewportView(artista);

        año.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        saño.setViewportView(año);

        duracion.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        sduracion.setViewportView(duracion);

        Agregar1.setBackground(new java.awt.Color(255, 51, 153));
        Agregar1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Agregar1.setText("Agregar");
        Agregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar1.setMargin(new java.awt.Insets(8, 14, 3, 14));
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });

        saliragregar.setBackground(new java.awt.Color(255, 51, 153));
        saliragregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        saliragregar.setText("Cancel");
        saliragregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saliragregar.setMargin(new java.awt.Insets(8, 14, 3, 14));
        saliragregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saliragregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saliragregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Labelartista, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(Labelcancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Labelalbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Labelaño, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labelduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sduracion, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(saño)
                            .addComponent(salbum)
                            .addComponent(scancion)
                            .addComponent(sartista))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addGap(0, 138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Labelcancion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(salbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Labelalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labelartista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(saño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Labelaño, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labelduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saliragregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar.getContentPane());
        Agregar.getContentPane().setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("Modificar");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel6.setText("Álbum");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel7.setText("Artista");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel8.setText("Año");

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel9.setText("Duración");

        botonguardarcambios.setBackground(new java.awt.Color(255, 102, 255));
        botonguardarcambios.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        botonguardarcambios.setText("Guardar cambios");
        botonguardarcambios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonguardarcambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonguardarcambiosMouseClicked(evt);
            }
        });
        botonguardarcambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarcambiosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(cambiarnombre);

        jScrollPane2.setViewportView(cambiaralbum);

        jScrollPane3.setViewportView(cambiarartista);

        jScrollPane4.setViewportView(cambiaran);

        jScrollPane5.setViewportView(cambiarduracion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonguardarcambios, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(botonguardarcambios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar.getContentPane());
        Modificar.getContentPane().setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel10.setText("Recursión");

        botongobinario.setBackground(new java.awt.Color(255, 102, 204));
        botongobinario.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        botongobinario.setText("Convertidor Binario");
        botongobinario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botongobinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botongobinarioActionPerformed(evt);
            }
        });

        botonmatrices.setBackground(new java.awt.Color(255, 102, 204));
        botonmatrices.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        botonmatrices.setText("Multiplicar Matrices");
        botonmatrices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonmatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmatricesActionPerformed(evt);
            }
        });

        backMenurecursion.setBackground(new java.awt.Color(255, 102, 204));
        backMenurecursion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        backMenurecursion.setText("Menu");
        backMenurecursion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backMenurecursion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenurecursionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backMenurecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonmatrices, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botongobinario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botongobinario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonmatrices, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backMenurecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RecursionLayout = new javax.swing.GroupLayout(Recursion.getContentPane());
        Recursion.getContentPane().setLayout(RecursionLayout);
        RecursionLayout.setHorizontalGroup(
            RecursionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RecursionLayout.setVerticalGroup(
            RecursionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel11.setText("Conversiones");

        botonbinariodecimal.setBackground(new java.awt.Color(255, 102, 255));
        botonbinariodecimal.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        botonbinariodecimal.setText("Binario a decimal");
        botonbinariodecimal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonbinariodecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbinariodecimalActionPerformed(evt);
            }
        });

        botondecimalbinario.setBackground(new java.awt.Color(255, 102, 255));
        botondecimalbinario.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        botondecimalbinario.setText("Decimal a binario");
        botondecimalbinario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botondecimalbinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondecimalbinarioActionPerformed(evt);
            }
        });

        backmenurecursion.setBackground(new java.awt.Color(255, 102, 255));
        backmenurecursion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        backmenurecursion.setText("Atras");
        backmenurecursion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backmenurecursion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backmenurecursionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backmenurecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botondecimalbinario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonbinariodecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonbinariodecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botondecimalbinario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backmenurecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ConversionesLayout = new javax.swing.GroupLayout(Conversiones.getContentPane());
        Conversiones.getContentPane().setLayout(ConversionesLayout);
        ConversionesLayout.setHorizontalGroup(
            ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ConversionesLayout.setVerticalGroup(
            ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setText("Proyecto Laboratorio P1");

        recursion.setBackground(new java.awt.Color(255, 102, 153));
        recursion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        recursion.setText("Recursion");
        recursion.setMargin(new java.awt.Insets(9, 14, 3, 14));
        recursion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recursionActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 102, 153));
        Salir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        Salir.setText("Salir");
        Salir.setMargin(new java.awt.Insets(9, 14, 3, 14));
        Salir.setName(""); // NOI18N
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        golabotify.setBackground(new java.awt.Color(255, 102, 153));
        golabotify.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        golabotify.setText("Labotify");
        golabotify.setMargin(new java.awt.Insets(9, 14, 3, 14));
        golabotify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                golabotifyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recursion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golabotify, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(golabotify, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(recursion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recursionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recursionActionPerformed
        Recursion.setVisible(true);
        Recursion.pack();
        Recursion.setLocationRelativeTo(this);
        Recursion.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        this.dispose();    }//GEN-LAST:event_recursionActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void golabotifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golabotifyMouseClicked

        Labotify.setVisible(true);
        Labotify.pack();
        Labotify.setLocationRelativeTo(this);
        Labotify.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        this.dispose();

    }//GEN-LAST:event_golabotifyMouseClicked

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        Labotify.dispose();
        Agregar.setVisible(true);
        Agregar.pack();
        Agregar.setLocationRelativeTo(this);
        Agregar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);


    }//GEN-LAST:event_agregarMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed

        JOptionPane.showMessageDialog(null, obtenercancion());
    }//GEN-LAST:event_listarActionPerformed

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked

        Labotify.dispose();
        this.setVisible(true);

    }//GEN-LAST:event_backmenuMouseClicked

    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
        String scancion = "";
        String salbum = "";
        String sartista = "";
        int san = 0;
        int sduracion = 0;

        Cancion agregar = new Cancion(scancion, salbum, sartista, san, sduracion);
        try {
            scancion = cancion.getText();
            salbum = album.getText();
            sartista = artista.getText();
            san = Integer.parseInt(año.getText());
            sduracion = Integer.parseInt(duracion.getText());
            agregar.setAlbum(album.getText());
            agregar.setArtista(artista.getText());
            agregar.setItem(song.size());
            agregar.setAño(Integer.parseInt(año.getText()));
            agregar.setDuracion(Integer.parseInt(duracion.getText()));

        } catch (Exception ex) {
        }

        song.add(new Cancion(scancion, salbum, sartista, san, sduracion));
        JOptionPane.showMessageDialog(null, "¡CANCION AGREGADA CON ÉXITO!");

        año.setText("");
        cancion.setText("");
        album.setText("");
        artista.setText("");
        duracion.setText("");
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void saliragregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saliragregarMouseClicked

        Agregar.dispose();
        Labotify.setVisible(true);


    }//GEN-LAST:event_saliragregarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        String result = "";
        int cont = 1;
        for (int i = 0; i < song.size(); i++) {
            Cancion c = song.get(i);
            result += cont + " - " + c.toString();
            cont++;
            result += "\n";
        }
        String num = JOptionPane.showInputDialog(null, result + "\n"
                + "Ingrese el indice de la cancion que desea eliminar: ");
        int indice = Integer.parseInt(num);
        if (indice <= song.size()) {
            cont = indice;
            indice = indice - 1;
            JOptionPane.showMessageDialog(null, "Se ha eliminado la canción:\n" + cont + ". " + song.get(indice).toString());
            song.remove(indice);
        } else {
            JOptionPane.showMessageDialog(null, "Indice no valido");
        }

    }//GEN-LAST:event_eliminarMouseClicked

    private void informacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionMouseClicked

        String result = "";
        int cont = 1;

        for (int i = 0; i < song.size(); i++) {
            Cancion c = song.get(i);
            result += cont + "- " + c.toString();
            cont++;
            result += "\n";
        }
        String num = JOptionPane.showInputDialog(null, result + "\n"
                + "Ingrese el indice de la cancion que desea ver: ");
        int indice = Integer.parseInt(num);
        if (indice <= song.size()) {
            indice = indice - 1;
            JOptionPane.showMessageDialog(null, song.get(indice).toStringcompleto());
        } else {
            JOptionPane.showMessageDialog(null, "Indice no valido");
        }

    }//GEN-LAST:event_informacionMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked

        String result = "";
        int cont = 1;
        for (int i = 0; i < song.size(); i++) {
            Cancion c = song.get(i);
            result += cont + "- " + c.toString();
            cont++;
            result += "\n";
        }
        String num = JOptionPane.showInputDialog(null, result + "\n"
                + "Ingrese el indice de la canción a editar: ");
        int indice = Integer.parseInt(num);

        if (indice <= song.size() && indice - 1 >= 0) {
            selectedindex = indice - 1;
            Labotify.dispose();
            Modificar.setVisible(true);
            Modificar.pack();
            Modificar.setLocationRelativeTo(this);
            Modificar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            indice = indice - 1;
            cambiarnombre.setText(song.get(indice).getCancion());
            cambiaralbum.setText(song.get(indice).getAlbum());
            cambiarartista.setText(song.get(indice).getArtista());
            cambiaran.setText(song.get(indice).antoString());
            cambiarduracion.setText(song.get(indice).duraciontoString());
        } else {
            JOptionPane.showMessageDialog(null, "Indice no valido");
        }

    }//GEN-LAST:event_modificarMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseClicked

    private void botonguardarcambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarcambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonguardarcambiosActionPerformed

    private void botonguardarcambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonguardarcambiosMouseClicked
        String scancion = "";
        String salbum = "";
        String sartista = "";
        int san = 0;
        int sduracion = 0;

        Cancion modificar = song.get(selectedindex);
        try {
            scancion = cambiarnombre.getText();
            salbum = cambiaralbum.getText();
            sartista = cambiarartista.getText();
            san = Integer.parseInt(cambiaran.getText());
            sduracion = Integer.parseInt(cambiarduracion.getText());
            modificar.setCancion(cambiarnombre.getText());
            modificar.setAlbum(cambiaralbum.getText());
            modificar.setArtista(cambiarartista.getText());
            modificar.setItem(song.size());
            modificar.setAño(Integer.parseInt(cambiaran.getText()));
            modificar.setDuracion(Integer.parseInt(cambiarduracion.getText()));

        } catch (Exception ex) {
        }

        // song.set(song.size(), );
        Modificar.dispose();
        Labotify.setVisible(true);
        Labotify.pack();
        Labotify.setLocationRelativeTo(this);
        Labotify.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_botonguardarcambiosMouseClicked

    private void backMenurecursionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenurecursionActionPerformed
        Recursion.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_backMenurecursionActionPerformed

    private void botondecimalbinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondecimalbinarioActionPerformed
        String binario = JOptionPane.showInputDialog(null, "Ingrese un numero: ");
        int num = Integer.parseInt(binario);

        JOptionPane.showMessageDialog(null, "El numero decimal "+binario+ " en binario: "+decToBin(num, ""));
    }//GEN-LAST:event_botondecimalbinarioActionPerformed

    private void botonbinariodecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbinariodecimalActionPerformed
        String binario = JOptionPane.showInputDialog(null, "Ingrese un numero binario: ");

        JOptionPane.showMessageDialog(null, "El numero binario "+binario+ " en decimal: "+binariodecimal(binario, binario.length() - 1, 0));
    }//GEN-LAST:event_botonbinariodecimalActionPerformed

    private void botongobinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botongobinarioActionPerformed
        Recursion.dispose();
        Conversiones.setVisible(true);
        Conversiones.pack();
        Conversiones.setLocationRelativeTo(this);
        Conversiones.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_botongobinarioActionPerformed

    private void botonmatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmatricesActionPerformed
        int fila_A = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las filas de la matriz 1: "));
        int columna_A = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las columnas de la matriz 1: "));
        int fila_B = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las filas de la matriz 2: "));
        int columna_B = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las filas de la matriz 2: "));

        if (columna_A == fila_B) {
            int[][] matriz_a = new int[fila_A][columna_A];
            int[][] matriz_b = new int[fila_B][columna_B];
            int[][] matriz_c = new int[fila_A][columna_B];
            matriz_a = llenado(matriz_a, matriz_a.length - 1, matriz_a[0].length - 1);
            matriz_b = llenado(matriz_b, matriz_b.length - 1, matriz_b[0].length - 1);
            matriz_c = multiplicacion(matriz_a, matriz_b, matriz_c, matriz_c.length - 1, matriz_c.length - 1);
            String output = "Matriz A: \n" +impresion(matriz_a, matriz_a.length - 1, matriz_a[0].length - 1,"") 
                    + '\n'
                    + "Matriz B: \n" +impresion (matriz_b, matriz_b.length - 1, matriz_b[0].length - 1, "")
                    +'\n'
                    +"Matriz C: \n" +impresion (matriz_c, matriz_c.length - 1, matriz_c[0].length - 1, "");
            JOptionPane.showMessageDialog(null,output);
        } else {
            JOptionPane.showMessageDialog(null,"El numero de columnas de la primera matriz debe ser el mismo numero de filas de la segunda");

        }
    }//GEN-LAST:event_botonmatricesActionPerformed

    private void backmenurecursionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backmenurecursionActionPerformed
        Conversiones.dispose();
        Recursion.setVisible(true);
    }//GEN-LAST:event_backmenurecursionActionPerformed

    public String obtenercancion() {
        String canciones = "";
        for (Cancion cancion : song) {
            canciones += Integer.toString(song.indexOf(cancion) + 1) + ". " + cancion.toString() + '\n';
        }
        return canciones;
    }

    public String decToBin(int dec, String bin) {
        if (dec == 0 || dec == 1) {
            return (char) (dec + 48) + bin;
        } else {
            return decToBin(dec / 2, (dec % 2) + bin);
        }
    }

    public int binariodecimal(String binario, int index, int resp) {
        if (index == 0) {
            int base = Integer.parseInt(Character.toString(binario.charAt(binario.length() - 1 - index))) * 2;
            return resp + (int) Math.pow(base, index);
        } else {
            int base = Integer.parseInt(Character.toString(binario.charAt(binario.length() - 1 - index))) * 2;
            return binariodecimal(binario, index - 1, resp + (int) Math.pow(base, index));

        }
    }

    public String impresion(int[][] matrix, int r_index, int c_index, String output) {
        if (r_index >= 0 && c_index >= 0) {
            output = '[' + Integer.toString(matrix[r_index][c_index]) + ']' + output;
        }

        if (r_index == 0 && c_index == 0) {
            return output;
        } else {
            if (c_index == 0) {
                output = '\n' + output;
                return impresion(matrix, r_index - 1, matrix[0].length - 1, output);
            } else {
                return impresion(matrix, r_index, c_index - 1, output);
            }
        }
    }

    public int[][] llenado(int[][] matrix, int f_index, int c_index) {
        if (f_index >= 0 && c_index >= 0) {
            matrix[f_index][c_index] = aleatorio.nextInt(9);
        }
        if (f_index == 0 && c_index == 0) {
            return matrix;
        } else {
            if (c_index == 0) {
                return llenado(matrix, f_index - 1, matrix[0].length - 1);
            } else {
                return llenado(matrix, f_index, c_index - 1);
            }
        }
    }

    public int rowProduct(int[][] matriz1, int[][] matriz2, int fila, int columna, int index, int resultado) {
        if (index == matriz1[0].length - 1) {
            resultado += matriz1[fila][index] * matriz2[index][columna];
            return resultado;
        } else {
            resultado += matriz1[fila][index] * matriz2[index][columna];
            return rowProduct(matriz1, matriz2, fila, columna, index + 1, resultado);

        }
    }

    public int[][] multiplicacion(int[][] matriz_a, int[][] matriz_b, int[][] matriz_c, int indexfila, int indexcolumna) {
        if (indexfila >= 0 && indexcolumna >= 0) {
            matriz_c[indexfila][indexcolumna] = rowProduct(matriz_a, matriz_b, indexfila, indexcolumna, 0, 0);
        }
        if (indexfila == 0 && indexcolumna == 0) {
            return matriz_c;
        } else {
            if (indexcolumna == 0) {
                return multiplicacion(matriz_a, matriz_b, matriz_c, indexfila - 1, matriz_c[0].length - 1);
            } else {
                return multiplicacion(matriz_a, matriz_b, matriz_c, indexfila, indexcolumna - 1);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar;
    private javax.swing.JButton Agregar1;
    private javax.swing.JDialog Conversiones;
    private javax.swing.JLabel Labelalbum;
    private javax.swing.JLabel Labelartista;
    private javax.swing.JLabel Labelaño;
    private javax.swing.JLabel Labelcancion;
    private javax.swing.JLabel Labelduracion;
    private javax.swing.JDialog Labotify;
    private javax.swing.JPanel Menu;
    private javax.swing.JDialog Modificar;
    private javax.swing.JDialog Recursion;
    private javax.swing.JButton Salir;
    private javax.swing.JButton agregar;
    private javax.swing.JTextPane album;
    private javax.swing.JTextPane artista;
    private javax.swing.JTextPane año;
    private javax.swing.JButton backMenurecursion;
    private javax.swing.JButton backmenu;
    private javax.swing.JButton backmenurecursion;
    private javax.swing.JButton botonbinariodecimal;
    private javax.swing.JButton botondecimalbinario;
    private javax.swing.JButton botongobinario;
    private javax.swing.JButton botonguardarcambios;
    private javax.swing.JButton botonmatrices;
    private javax.swing.JTextPane cambiaralbum;
    private javax.swing.JTextPane cambiaran;
    private javax.swing.JTextPane cambiarartista;
    private javax.swing.JTextPane cambiarduracion;
    private javax.swing.JTextPane cambiarnombre;
    private javax.swing.JTextPane cancion;
    private javax.swing.JTextPane duracion;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton golabotify;
    private javax.swing.JButton informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton listar;
    private javax.swing.JButton modificar;
    private javax.swing.JButton recursion;
    private javax.swing.JScrollPane salbum;
    private javax.swing.JButton saliragregar;
    private javax.swing.JScrollPane sartista;
    private javax.swing.JScrollPane saño;
    private javax.swing.JScrollPane scancion;
    private javax.swing.JScrollPane sduracion;
    // End of variables declaration//GEN-END:variables
//cancion = new ArrayList<>();
    Cancion c;
    int selectedindex;
}
